In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [7]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [6]:
a_centered = a - mean_a

a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [13]:
A = a_centered[:, 0]

A

array([-1.,  0.,  1.,  1., -1.])

In [12]:
B = a_centered[:, 1]

B

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [14]:
a_centered_sp = A @ B

a_centered_sp

8.0

In [16]:
N = a.shape[0]
N

5

In [18]:
print(a_centered_sp / (N-1))

2.0


In [19]:
a_t = np.transpose(a)
a_t

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [20]:
G = np.cov(a_t)
G

array([[1. , 2. ],
       [2. , 4.3]])

In [21]:
G[0,1]

2.0